version: '3.5'

services:

  database:
    image: mongo:4.4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_username
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: mongo_database
    volumes:
      - ./database/seeders:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    depends_on:
      - database
    image: node:14.16-slim
    restart: always
    environment:
      NODE_ENV: 'development'
      PORT: 3000
      DATABASE_URI: 'mongodb://database:27017/mongo_database'
      DATABASE_USERNAME: mongo_username
      DATABASE_PASSWORD: mongo_password
    working_dir: /backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
    networks:
      - app-network
    command: bash -c "yarn && yarn dev"

  frontend:
    depends_on:
      - backend
    image: node:14.16-slim
    restart: always
    environment:
      NODE_ENV: 'development'
      PORT: 4200
    working_dir: /frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network
    command: bash -c "yarn && yarn start"

networks:
  app-network:
